version: '3'
services:
  neo4j:
    image: neo4j:5.11.0
    restart: no
    hostname: neo4j
    container_name: neo4j_container
    volumes:
      - $HOME/neo4j/plugins:/plugins
      - $HOME/neo4j/import/:/var/lib/neo4j/import
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_apoc_export_file_enabled=true 
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      # - NEO4J_dbms_security_procedures_unrestricted=apoc.,n10s.,semantics.*
      # - NEO4J_dbms_unmanaged__extension__classes='semantics.extension'='/rdf'
    tmpfs:
      - /var/lib/neo4j/run